[project]
name = "budgetme_backend"
version = "0.1.0"
author = ["Jakub Matuszak"]
description = "Add your description here"
readme = "README.md"

requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.115.0",
    "sqlmodel>=0.0.22",
    "pydantic>=2.10.0",
]
